# -*- coding: utf-8 -*-
"""Resume matching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bT_OiBrbDeZq4EVeIIqk56dFQLFQ1Gmh
"""

!pip install spacy scikit-learn pandas

!python -m spacy download en_core_web_sm

import pandas as pd
import spacy
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import kagglehub

# Download latest version
path = kagglehub.dataset_download("snehaanbhawal/resume-dataset")

print("Path to dataset files:", path)

import os

# Show all files in the dataset folder
print("Dataset path:", path)
print("Files inside dataset folder:", os.listdir(path))

df = pd.read_csv(f"/kaggle/input/resume-dataset/Resume/Resume.csv")

print(df.columns)

df = df[['Category', 'Resume_str']].dropna().reset_index(drop=True)

!python -m spacy download en_core_web_sm
nlp = spacy.load("en_core_web_sm")

job_description = """
We are looking for an AI Generalist with experience in Python, NLP, Machine Learning,
TensorFlow or PyTorch, and data pipeline building.
"""

job_desc_cleaned = clean_text(job_description)

def clean_text(text):
    doc = nlp(text.lower())
    tokens = [token.lemma_ for token in doc if not token.is_stop and token.is_alpha]
    return " ".join(tokens)


df["Cleaned_Resume"] = df["Resume_str"].apply(clean_text)

tfidf_matrix = vectorizer.fit_transform(df["Cleaned_Resume"].tolist() + [job_desc_cleaned])

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df["Cleaned_Resume"].tolist() + [job_desc_cleaned])

cosine_sim = cosine_similarity(tfidf_matrix[-1], tfidf_matrix[:-1]).flatten()

df["Match_Score"] = cosine_sim

df = df.sort_values(by="Match_Score", ascending=False)

print("Top Matching Candidates:")
print(df[["Category", "Match_Score"]].head(10))